// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternating_text: dynamic(() => import("./AlternatingText")),
  big_text: dynamic(() => import("./BigText")),
  can_sky_dive: dynamic(() => import("./CanSkyDive")),
  carousel: dynamic(() => import("./Carousel")),
  hero: dynamic(() => import("./Hero")),
};
